-- Criar tabela WALLETS se ela não existir
CREATE TABLE IF NOT EXISTS WALLETS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    CPF BIGINT,
    EMAIL VARCHAR(100),
    `PASSWORD` VARCHAR(100),
    `TYPE` INT,
    BALANCE DECIMAL(10, 2),
    `VERSION` BIGINT
);

-- Criar tabela TRANSACTIONS se ela não existir
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    `VALUE` DECIMAL(10, 2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
);

